service: serverless-eventing

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: web-handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
