service: serverless-eventing


plugins:
  - serverless-offline

custom:
  defaults:
    log_level: INFO
    stage: dev
  config: ${file(./config/variables.yml):${opt:stage, self:custom.defaults.stage}}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaults.stage}
  region: us-east-1
  environment: ${file(./config/env.yml):${opt:stage, self:custom.defaults.stage}}
  
functions:
  rulesApi:
    handler: functions/rulesApi/handler.httpApp
    events:
      - http:
          method: GET
          path: rules/getAll
          cors: true
      - http:
          method: POST
          path: rules
          cors: true
      - http:
          method: GET
          path: alerts/getAll
          cors: true

  debugApp:
    handler: functions/debugWeb/handler.httpApp
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  # does not run via serverless-offline
  ruleProcessor:
    private: true
    handler: functions/ruleProcessor/handler.streamProcessor
    # memorySize: 128
    # timeout: 10
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.config.eventsStreamArn}
          batchSize: 100
          startingPosition: LATEST

  alertProcessor:
    private: true
    handler: functions/alertProcessor/handler.streamProcessor
    # memorySize: 128
    # timeout: 10
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.config.alertsStreamArn}
          batchSize: 100
          startingPosition: LATEST