service: serverless-eventing


plugins:
  - serverless-offline

custom:
  defaults:
    log_level: INFO
    stage: dev
  config: ${file(./config/variables.yml):${opt:stage, self:custom.defaults.stage}}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaults.stage}
  region: us-east-1
  environment: ${file(./config/offline.yml)}
  
functions:
  app:
    handler: web-handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  # does not run via serverless-offline
  ruleProcessor:
    private: true
    handler: stream-handler.handler
    # memorySize: 128
    # timeout: 10
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.config.streamArn}
          batchSize: 100
          startingPosition: LATEST