---
offline:
  eventsStreamArn: 'arn:aws:kinesis:us-east-1:example:stream/offline-events'
  alertsStreamArn: 'arn:aws:kinesis:us-east-1:example:stream/offline-alerts'
  
dev:
  eventsStreamArn: 
    'Fn::ImportValue': 'some-other-service:${self:provider.stage}:StreamARN'
  alertsStreamArn: 
    'Fn::ImportValue': 'some-other-service:${self:provider.stage}:StreamARN'
